# Read this Post for runing processis in parallel
# https://stackoverflow.com/questions/42979271/how-to-run-multiple-instances-of-the-same-python-script-which-uses-subprocess-ca
# 
# How to use this program
# srun python s2_chk_styl_ana_app_ARR.py -t 577 -pd ../my_codesnippet_analysis/Compiles/mvn_apps -upd -cf ../my_codesnippet_analysis/Compiles/compilesnippets_java -ucf -ncf ../my_codesnippet_analysis/Compiles/nocompilesnippets_java -lf ../my_codesnippet_analysis/Compiles/nocompile_logs.txt

# srun python s2_chk_styl_ana_app_ARR.py -idx "${SLURM_ARRAY_TASK_ID}" -t 577 -crd ../my_codesnippet_analysis/Compiles -ucrd -pd mvn_apps -upd -ncf nocompilesnippets_java -lf nocompile_logs.txt




import subprocess as sp
# what will be used to read files
import glob
import shutil
import os
import re

import xml.etree.ElementTree as ET
#from xml.dom import minidom

import argparse

parser = argparse.ArgumentParser(
    description='Run Compile on Java Apps.'
)

parser.add_argument(
    "-idx",
    "--arrayid",
    type=str,
    help="Enter SLURM ARRAY TASK ID"
)

parser.add_argument(
    "-n",
    "--size",
    default=577,
    type=int,
    help="Enter number of jobs to execute"
)

parser.add_argument(
    "-ucrd",
    "--usecommonrootdir",
    action="store_true",
    help="Use common root directory"
)
#e.g. ../my_codesnippet_analysis/Compiles
parser.add_argument(
    "-crd",
    "--commonrootdir",
    help="Use common root directory"
)

parser.add_argument(
    "-upd",
    "--useparentdest",
    action="store_true",
     help="Parent path where multiple folders will be generated (before the autogenerated folders)"
    
)

#e.g., ../my_codesnippet_analysis/Compiles/mvn_apps
#e.g., mvn_apps   (if usecommonrootdir is true)
parser.add_argument(
    "-pd",
    "--parentdest",
    type=str, 
     help="Parent path where multiple folders will be generated (before the autogenerated folders)"
    
)

parser.add_argument(
    "-a",
    "--app",
    default='my-javacodeanalysis-app',
    help="Enter general application name that will be auto generated e.g my-javacodeanalysis-app with will be appended with numbers 0, 1, ..., n"
)

parser.add_argument(
    "-t",
    "--sourcetype",
    default="java",
    type=str,
    help="Enter source type java, py, cpp"
)

parser.add_argument(
    "-cd",
    "--childdest",
    default="src/main/java",
    type=str, 
     help="The child destination path(s) where the multiple subfolders you want to copy files to (after the autogenerated folders)"
)


parser.add_argument(
    "-p",
    "--pkg",
    default='myjavacodeanalysis',
    help="Enter the package name you want each class to have or the java files to be moved to"
)

#e.g. ../my_codesnippet_analysis/Compiles/checkstyle_logs.txt
#e.g., checkstyle_logs.txt  (if usecommonrootdir is true)
parser.add_argument(
    "-lf",
    "--logfile",
    help="Enter logation to logfile"
)
#e.g., ../my_codesnippet_analysis/Compiles/checkstylecompletesnippets_java
#e.g., checkstylecompletesnippets_java  (if usecommonrootdir is true)
parser.add_argument(
    "-cf",
    "--compilefiles",
    help="Location to save the compiled Java Files"
)

parser.add_argument(
    "-ucf",
    "--usecompilefiles",
    action="store_true",
    help="Location to save the compiled Java Files"
)

parser.add_argument(
    "-mcf",
    "--movecompletefiles",
    action="store_true",
    help="Put this to move complete files"
)

#e.g., ../my_codesnippet_analysis/Compiles/checkstyleerrorsnippets_java
#e.g., checkstyleerrorsnippets_java  (if usecommonrootdir is true)
parser.add_argument(
    "-ncf",
    "--nocompilefiles",
    help="Location to save the Java Files that did not compile"
)




args = parser.parse_args()

array_id = args.arrayid
size = args.size
java_pkg = args.pkg
java_app = args.app
src_type = args.sourcetype
use_parent_dest_path = args.useparentdest
parent_dest_path = args.parentdest
use_comm_root_dir = args.usecommonrootdir
comm_root_dir = args.commonrootdir
child_dest_path = args.childdest
log_file = args.logfile
use_comp_java_files = args.usecompilefiles
comp_java_files = args.compilefiles
move_comp_files = args.movecompletefiles
nocompile_java_files = args.nocompilefiles




####################################################################
# Run Checkstyle static code analysis
###################################################################

def run_chk_styl_analysis():
        
    #e.g. my-javacodeanalysis-app0
    app_name_full = '{}{}'.format(java_app, array_id)
    
    #e.g. my-javacodeanalysis-app0
    app_name_full_dest_path = app_name_full
    
    
    if use_comm_root_dir == True and use_parent_dest_path == True:
        #e.g., ../my_codesnippet_analysis/CheckStyle3/mvn_apps/my-javacodeanalysis-app0
        app_name_full_dest_path = '{}/{}/{}'.format(comm_root_dir, parent_dest_path, app_name_full)
    elif use_comm_root_dir == True:
        #e.g., ../my_codesnippet_analysis/CheckStyle3/mvn_apps/my-javacodeanalysis-app0
        app_name_full_dest_path = '{}/{}'.format(comm_root_dir, app_name_full)
    elif use_parent_dest_path == True:
        app_name_full_dest_path = '{}/{}'.format(parent_dest_path, app_name_full)
        
    #print('@@ {}'.format(app_name_full_parent_dest_path))
    
    #e.g., ../my_codesnippet_analysis/CheckStyle3/mvn_apps/my-javacodeanalysis-app0/src/main/java
    app_name_full_child_dest_path = '{}/{}'.format(app_name_full_dest_path, child_dest_path)
    #e.g., ../my_codesnippet_analysis/CheckStyle3/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis
    app_name_full_child_dest_path_pkg = '{}/{}'.format(app_name_full_child_dest_path, java_pkg)
    
    log_file_full = log_file
    comp_java_files_full = comp_java_files
    nocompile_java_files_full = nocompile_java_files
    
    
    if use_comm_root_dir == True:
        #e.g. ../my_codesnippet_analysis/CheckStyle3/checkstyle_logs.txt
        log_file_full = '{}/{}'.format(comm_root_dir, log_file)
        #e.g., ../my_codesnippet_analysis/CheckStyle3/checkstyleerrorsnippets_java
        nocompile_java_files_full = '{}/{}'.format(comm_root_dir, nocompile_java_files)
        
        if use_comp_java_files == True:
            #e.g., ../my_codesnippet_analysis/CheckStyle3/checkstylecompletesnippets_java
            comp_java_files_full = '{}/{}'.format(comm_root_dir, comp_java_files)
        
        
    
        
        
    error = True
    count = 0
        
    while error:
        #compile_pkg_cmd = 'cd ../my_codesnippet_analysis/CheckStyle3/mvn_apps/my-javacodeanalysis-app0; mvn -e compile package'
        compile_pkg_cmd = 'cd {}; mvn -e compile package'.format(app_name_full_dest_path)
        cmd1 = sp.run(
            compile_pkg_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )
        
        # capture the output 
        log_msg = cmd1.stdout
        #log_msg = 'ERROR'

        # Perform some text processing
        # 1. capture the error msg and save it into a log file

        # Open a file with access mode 'a'
        #with open("checkstyle_logs.txt", "a") as file_object:
        with open(log_file_full, "a") as file_object:
            
            # Append log_msg at the end of file
            file_object.write(log_msg)
            
        # If there is error in the log file
        if 'ERROR' in log_msg: 

            error = True
            # 2. retrieve the erroneous file
            pattern = re.compile(r'Code_\d+_\d+_\d+_\d+\.java')
            #pattern = re.compile(r'Code_\d+_\d+_\d+_\d+\.{}'.format(src_type))
            #filename_match = pattern.findall(log_msg)[0]
            filename_matchs = pattern.findall(log_msg)
            # remove duplicates in the classnames 
            # and convert list to space saparated
            filename_matchs_str = ' '.join(list(set(filename_matchs)))
            
            # move it to a nocompile_java
            #filename_match ='Code_52604169_52604034_2681_0.java'
            #if len(filename_match) > 0:
            #    filename_match = filename_match[0]
                # print(filename_matche)

            # 3. Move the erroneous file to another folder 'checkstyleerrorsnippets_java'
            #e.g., mv_erroneous_file_cmd = 'mv ../my_codesnippet_analysis/CheckStyle3/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis/Code_1_1_1_1.java' ../my_codesnippet_analysis/CheckStyle3/checkstyleerrorsnippets_java'
            mv_erroneous_file_cmd = 'mv {}/{} {}'.format(app_name_full_child_dest_path_pkg, filename_matchs_str, nocompile_java_files_full)
            cmd2 = sp.run(
                mv_erroneous_file_cmd, # command
                capture_output=True,
                text=True,
                shell=True
            )
                   
        else: # else If there is error when carring out the checkstyle
            error = False

        count = count + 1
        # 4. re-run the comand until all the error files have been eliminated

        
    #2. Move the java files of thoes that completed into a checkstylecompletesnippets_java
    # e.g., mv_complete_file_cmd = 'mv ../my_codesnippet_analysis/CheckStyle3/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis/*.java ../my_codesnippet_analysis/CheckStyle3/checkstylecompletesnippets_java'
    if move_comp_files == True:
        mv_complete_file_cmd = 'mv {}/*.{} {}'.format(app_name_full_child_dest_path_pkg, src_type, comp_java_files_full)
        cmd3 = sp.run(
            mv_complete_file_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )
      
    

    
# Run the CheckStyle Analysis
run_chk_styl_analysis()

print('CheckStyle Analysis Complete Rank {} -:)'.format(array_id))
# Next step
# 1. mv all the other .java files in the apps that did not complete into checkstyleincompletesnippets_java files
# 2. split it equally
# 3. redistribut it amoungs the maven apps again
# 4. Run the check style again