# Read this Post for runing processis in parallel
# https://stackoverflow.com/questions/42979271/how-to-run-multiple-instances-of-the-same-python-script-which-uses-subprocess-ca
# 
# How to use this program

## srun python s2_mk_multi_mvn_apps_n_move_files_4m_multi_apps_ARR.py -idx "${SLURM_ARRAY_TASK_ID}" -n 577 -s ../my_codesnippet_analysis/CheckStyle1/mvn_apps -ucs -crd ../my_codesnippet_analysis/SpotBugs1 -ucrd -pd mvn_apps -upd -libs checks_lib -rvaf -ctarf -ctsf -upxf -acsc -asiexml


# To run it on slum:
# $    sbatch s1_mk_multiple_maven_apps_n_move_files_ARR.sl 


# Fetch the Files 
# Divide the Files equaliy according to the number
# Generate the Maven Applications based on the number of files
# delete the initial App.java file created by default
# Update the Pom.xml File to suite
# add google check.xml


import subprocess as sp
# what will be used to read files
import glob
import shutil
import os
import numpy as np
import re

import xml.etree.ElementTree as ET
#from xml.dom import minidom

import argparse

parser = argparse.ArgumentParser(
    description='Run CheckStyle on Java Apps.'
)

parser.add_argument(
    "-idx",
    "--arrayid",
    default="java",
    type=str,
    help="Enter SLURM ARRAY TASK ID"
)

parser.add_argument(
    "-n",
    "--size",
    default=577,
    type=int,
    help="Enter number of jobs to execute"
)

#e.g. ../my_codesnippet_analysis/CheckStyle1
parser.add_argument(
    "-s",
    "--source",
    help="Enter the location of the source folder to fetch (copy or move) the source code files from e.g java, py, cpp"
)
parser.add_argument(
    "-sga",
    "--srcgenapp",
    default='my-javacodeanalysis-app',
    help="Enter general application name that will be auto generated e.g my-javacodeanalysis-app with will be appended with numbers 0, 1, ..., n"
)
parser.add_argument(
    "-ucs",
    "--usechildsource",
    action="store_true",
     help="Agree to use child source"   
)
parser.add_argument(
    "-cs",
    "--childsource",
    default="src/main/java/myjavacodeanalysis",
    help="Enter the location of the source folder to fetch (copy or move) the source code files"
)

# command -mv ---> sets mv to True
# command --->sets mv to False
#https://stackoverflow.com/questions/60999816/argparse-not-parsing-boolean-arguments
parser.add_argument(
    "-mv",
    "--movesource", 
    action="store_true",
    help="Move rather than copy the source codes files"
)

parser.add_argument(
    "-t",
    "--sourcetype",
    default="java",
    type=str,
    help="Enter source type java, py, cpp"
)

parser.add_argument(
    "-ucrd",
    "--usecommonrootdir",
    action="store_true",
    help="Use common root directory"
)
#e.g. ../my_codesnippet_analysis/SpotBugs1
parser.add_argument(
    "-crd",
    "--commonrootdir",
    help="Use common root directory"
)

parser.add_argument(
    "-upd",
    "--useparentdest",
    action="store_true",
     help="Agree to use parent destination"   
)

#e.g. ../my_codesnippet_analysis/SpotBugs1/mvn_apps
parser.add_argument(
    "-pd",
    "--parentdest",
    default=".",
    type=str, 
     help="Parent path where multiple folders will be generated (before the autogenerated folders)"   
)

parser.add_argument(
    "-dga",
    "--destgenapp",
    default='my-javacodeanalysis-app',
    help="Enter general application name that will be auto generated e.g my-javacodeanalysis-app with will be appended with numbers 0, 1, ..., n"
)

parser.add_argument(
    "-cd",
    "--childdest",
    default="src/main/java",
    type=str, 
     help="The child destination path(s) where the multiple subfolders you want to copy files to (after the autogenerated folders)"
)


# command -rvaf ---> sets rva to True
# command --->sets rv to False
#https://stackoverflow.com/questions/60999816/argparse-not-parsing-boolean-arguments
parser.add_argument(
    "-rvaf",
    "--removeautogenfile", 
    action="store_true",
    help="removes the previous apps if they exist before creating a new one"
)
parser.add_argument(
    "-raf",
    "--autogenfileremove",
    default="App.java",
    type=str,
    help="Enter the name of an auto generated class that is created along with the maven app that you want removed. e.g App.java"
)

parser.add_argument(
    "-p",
    "--pkg",
    default='myjavacodeanalysis',
    help="Enter the package name you want each class to have or the java files to be moved to"
)


parser.add_argument(
    "-acsc",
    "--addcheckstylexmlchecks",
    action="store_true",
     help="update pom xml folder"   
)
parser.add_argument(
    "-csc",
    "--checkstylexmlchecks", 
    default="google_checks.xml",
    type=str,
    help="Enter the full name of the checks file plus extension (default is the google_checks.xml which will be auto included in the root directory where the pom.xml is located)."
)


parser.add_argument(
    "-cscst",
    "--checkstycompilersourcetarget", 
    default="17",
    type=str,
    help="Enter the check style version"
)


parser.add_argument(
    "-cv",
    "--checkstyleversion", 
    default="9.1",
    type=str,
    help="Enter the check style version"
)

parser.add_argument(
    "-mcpv",
    "--mavencheckstylepluginversion", 
    default="3.1.2",
    type=str,
    help="Enter the maven checkstyle plugin version"
)

parser.add_argument(
    "-mcp",
    "--mavencheckstyleplugin", 
    default="maven-checkstyle-plugin",
    type=str,
    help="Enter the maven checkstyle plugin"
)


# e.g. checks_lib
parser.add_argument(
    "-libs",
    "--libdir",
    type=str,
    help="Enter the path to copy the checks file from."
)

parser.add_argument(
    "-asiexml",
    "--addspotbugsincludeexcludexml",
    action="store_true",
     help="update pom xml folder"   
)

parser.add_argument(
    "-sixml",
    "--spotbugsincludexml",
    default="spotbugs-include.xml",
    type=str,
    help="Enter the path to copy the checks file to. (if you do not want it to be in the root dir with the pom.xml)."
)
parser.add_argument(
    "-sexml",
    "--spotbugsexcludexml",
    default="spotbugs-exclude.xml",
    type=str,
    help="Enter the path to copy the checks file to. (if you do not want it to be in the root dir with the pom.xml)."
)

parser.add_argument(
    "-pt",
    "--pattern",
    default="",
    type=str,
    help="Are there particular pattern of files you want to select."
)

parser.add_argument(
    "-tarf",
    "--targetfolder",
    default="target",
    type=str,
    help="Enter path to target folder"
)

parser.add_argument(
    "-ctarf",
    "--copytargetfolder",
    action="store_true",
     help="copy target folder"   
)

parser.add_argument(
    "-tsf",
    "--testfolder",
    default="src/test",
    type=str,
    help="Enter path totest folder"
)

parser.add_argument(
    "-ctsf",
    "--copytestfolder",
    action="store_true",
     help="copy target folder"   
)

parser.add_argument(
    "-upxf",
    "--updatepomxml",
    action="store_true",
     help="update pom xml folder"   
)




 

args = parser.parse_args()

array_id = args.arrayid
size = args.size
src_gen_app = args.srcgenapp
dest_gen_app = args.destgenapp
pkg_name = args.pkg
src = args.source
use_child_src = args.usechildsource
child_src = args.childsource
src_type = args.sourcetype
mv_src = args.movesource
rm_auto_gen_file = args.removeautogenfile
auto_gen_file_rm = args.autogenfileremove
use_comm_root_dir = args.usecommonrootdir
comm_root_dir = args.commonrootdir
pattern = args.pattern
use_parent_dest_path = args.useparentdest
parent_dest_path = args.parentdest
child_dest_path = args.childdest
copy_target_folder_path = args.copytargetfolder
target_folder_path = args.targetfolder
copy_test_folder_path = args.copytestfolder
test_folder_path = args.testfolder
update_pom_xml_file = args.updatepomxml

add_checkstyle_xml_checks = args.addcheckstylexmlchecks
checkstyle_xml_checks = args.checkstylexmlchecks
checkstyle_compiler_source_tagret = args.checkstycompilersourcetarget
checkstyle_version = args.checkstyleversion
maven_checkstyle_plugin_version = args.mavencheckstylepluginversion
maven_checkstyle_plugin = args.mavencheckstyleplugin

lib_path = args.libdir

add_spot_bug_include_exclude_xml = args.addspotbugsincludeexcludexml
spot_bug_include_xml = args.spotbugsincludexml
spot_bug_exclude_xml = args.spotbugsexcludexml


pkg_name_full=pkg_name
app_name_partial=dest_gen_app

def add_checkstyle_plugins_to_pom_xml(plugins):
    
    ######### add the checkstyle plugins into pom.xml ##########
    # <build><pluginManagement><plugins><plugin>
    plugin = plugins.makeelement('plugin', attrib)
    plugins.append(plugin)

    # <build><pluginManagement><plugins><plugin><groupId>
    groupId = plugin.makeelement('groupId', attrib)
    groupId.text = 'org.apache.maven.plugins'
    plugin.append(groupId)

    # <build><pluginManagement><plugins><plugin><artifactId>
    artifactId = plugin.makeelement('artifactId', attrib)
    artifactId.text = maven_checkstyle_plugin
    plugin.append(artifactId)

    # <build><pluginManagement><plugins><plugin><version>
    version = plugin.makeelement('version', attrib)
    version.text = maven_checkstyle_plugin_version
    plugin.append(version)


    # <build><pluginManagement><plugins><plugin><dependencies>
    dependencies = plugin.makeelement('dependencies', attrib)
    plugin.append(dependencies)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency>
    dependency = dependencies.makeelement('dependency', attrib)
    dependencies.append(dependency)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency><groupId>
    groupId = dependency.makeelement('groupId', attrib)
    groupId.text = 'com.puppycrawl.tools'
    dependency.append(groupId)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency><artifactId>
    artifactId = dependency.makeelement('artifactId', attrib)
    artifactId.text = 'checkstyle'
    dependency.append(artifactId)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency><version>
    version = dependency.makeelement('version', attrib)
    version.text = checkstyle_version
    dependency.append(version)

    # <build><pluginManagement><plugins><plugin><executions>
    executions = plugin.makeelement('executions', attrib)
    plugin.append(executions)

    # <build><pluginManagement><plugins><plugin><executions><execution>
    execution = executions.makeelement('execution', attrib)
    executions.append(execution)

    # <build><pluginManagement><plugins><plugin><executions><execution><id>
    ids = execution.makeelement('id', attrib)
    ids.text = 'checkstyle'
    execution.append(ids)

    # <build><pluginManagement><plugins><plugin><executions><execution><phase>
    phase = execution.makeelement('phase', attrib)
    phase.text = 'validate'
    execution.append(phase)

    # <build><pluginManagement><plugins><plugin><executions><execution><goals>
    goals = execution.makeelement('goals', attrib)
    execution.append(goals)

    # <build><pluginManagement><plugins><plugin><executions><execution><goals><goal>
    goal = goals.makeelement('goal', attrib)
    goal.text = 'check'
    goals.append(goal)

    # <build><pluginManagement><plugins><plugin><executions><execution><configuration>
    configuration = execution.makeelement('configuration', attrib)
    execution.append(configuration)

    # <build><pluginManagement><plugins><plugin><executions><execution><configuration><configLocation>
    configLocation = configuration.makeelement('configLocation', attrib)
    configLocation.text = checkstyle_xml_checks
    configuration.append(configLocation)

    # <build><pluginManagement><plugins><plugin><executions><execution><configuration><encoding>
    encoding = configuration.makeelement('encoding', attrib)
    encoding.text = 'UTF-8'
    configuration.append(encoding)

    # <build><pluginManagement><plugins><plugin><executions><execution><configuration><failsOnError>
    failsOnError = configuration.makeelement('failsOnError', attrib)
    failsOnError.text = 'false'
    configuration.append(failsOnError)

    # <build><pluginManagement><plugins><plugin><executions><execution><configuration><failOnViolation>
    failOnViolation = configuration.makeelement('failOnViolation', attrib)
    failOnViolation.text = 'false'
    configuration.append(failOnViolation)
    
    ###### Add the reporting plugins into the 'reporting' of the pom.xml #######
    ## this may not be required
    
    #<reporting>
    reporting = root.makeelement('reporting', attrib)
    root.append(reporting)

    #<reporting><plugins>
    plugins = reporting.makeelement('plugins', attrib)
    reporting.append(plugins)

    #<reporting><plugins><plugin>
    plugin = plugins.makeelement('plugin', attrib)
    plugins.append(plugin)

    #<reporting><plugins><plugin><groupId>
    groupId = plugin.makeelement('groupId', attrib)
    groupId.text = 'org.apache.maven.plugins'
    plugin.append(groupId)

    #<reporting><plugins><plugin><artifactId>
    artifactId = plugin.makeelement('artifactId', attrib)
    artifactId.text = maven_checkstyle_plugin
    plugin.append(artifactId)

    #<reporting><plugins><plugin><version>
    version = plugin.makeelement('version', attrib)
    version.text = maven_checkstyle_plugin_version
    plugin.append(version)

    #<reporting><plugins><plugin><configuration>
    configuration = plugin.makeelement('configuration', attrib)
    plugin.append(configuration)

    #<reporting><plugins><plugin><configuration><configLocation>
    configLocation = configuration.makeelement('configLocation', attrib)
    configLocation.text = checkstyle_xml_checks
    configuration.append(configLocation)

    #<reporting><plugins><plugin><configuration><failsOnError>
    failsOnError = configuration.makeelement('failsOnError', attrib)
    failsOnError.text = 'false'
    configuration.append(failsOnError)

    #<reporting><plugins><plugin><configuration><failOnViolation>
    failOnViolation = configuration.makeelement('failOnViolation', attrib)
    failOnViolation.text = 'false'
    configuration.append(failOnViolation)

    
    return plugins

    
def add_spotbugs_plugins_to_pom_xml(plugins):
    ######### update the 'build' tag with the sportbug requirements ##########
    
    # <build><pluginManagement><plugins><plugin>
    plugin = plugins.makeelement('plugin', attrib)
    plugins.append(plugin)
    
    # <build><pluginManagement><plugins><plugin><groupId>
    groupId = plugin.makeelement('groupId', attrib)
    groupId.text = 'com.github.spotbugs'
    plugin.append(groupId)
    
    # <build><pluginManagement><plugins><plugin><artifactId>
    artifactId = plugin.makeelement('artifactId', attrib)
    artifactId.text = 'spotbugs-maven-plugin' #spotbugs_mvn_plugin
    plugin.append(artifactId)

    # <build><pluginManagement><plugins><plugin><version>
    version = plugin.makeelement('version', attrib)
    version.text = '4.4.2.2' #spotbugs_mvn_plugin_version
    plugin.append(version)

    # <build><pluginManagement><plugins><plugin><executions><execution><configuration>
    configuration = plugin.makeelement('configuration', attrib)
    plugin.append(configuration)
    includeFilterFile = configuration.makeelement('includeFilterFile', attrib)
    includeFilterFile.text = spot_bug_include_xml #'spotbugs-include.xml'
    configuration.append(includeFilterFile)
    
    excludeFilterFile = configuration.makeelement('excludeFilterFile', attrib)
    excludeFilterFile.text = spot_bug_exclude_xml #'spotbugs-exclude.xml' 
    configuration.append(excludeFilterFile)

    
    # <build><pluginManagement><plugins><plugin><dependencies>
    dependencies = plugin.makeelement('dependencies', attrib)
    plugin.append(dependencies)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency>
    dependency = dependencies.makeelement('dependency', attrib)
    dependencies.append(dependency)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency><groupId>
    groupId = dependency.makeelement('groupId', attrib)
    groupId.text = 'com.github.spotbugs'
    dependency.append(groupId)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency><artifactId>
    artifactId = dependency.makeelement('artifactId', attrib)
    artifactId.text = 'spotbugs'
    dependency.append(artifactId)

    # <build><pluginManagement><plugins><plugin><dependencies><dependency><version>
    version = dependency.makeelement('version', attrib)
    version.text = '4.5.0'  #spotbugs_version
    dependency.append(version)
    
    return plugins

    
########################################################
# Updates the pom.xml file with checkstyle requirements #
########################################################
def update_pom_xml(
    app_name
):
    
    ####### Retrieve the pom.xml file from the java app #######
    pom_xml = '{}/pom.xml'.format(app_name)
    #tree = ET.parse('pom.xml')
    tree = ET.parse(pom_xml)
    
    root = tree.getroot()

    ###### Register namespace ######
    # retrieve 'http://maven.apache.org/POM/4.0.0' from root tag '{http://maven.apache.org/POM/4.0.0}project'
    pattern = re.compile(r'(https?:\/\/(www\.)?\w+\.\w+.\w+\/\w+\/\d+\.\d+\.\d)')
    root_namespace = pattern.findall(root.tag)[0][0]
   
    #ET.register_namespace('', "http://maven.apache.org/POM/4.0.0")
    ET.register_namespace('', root_namespace)

    # instantiate empty attributes
    attrib = {}

    # <properties>
    properties = root[6]
    # <properties><maven.compiler.source>
    source = properties[1]
    # <properties><maven.compiler.target>
    target = properties[2]
    
    # update the text
    source.text = checkstyle_compiler_source_tagret #17
    target.text = checkstyle_compiler_source_tagret #17
    
    
    # get the build
    # <build>
    build = root[8]
    # <build><pluginManagement>
    pluginManagement = build[0]
    # <build><pluginManagement><plugins>
    plugins = pluginManagement[0]

    
    if add_checkstyle_xml_checks == True:
        add_checkstyle_plugins_to_pom_xml(plugins)
        
    if add_spot_bug_include_exclude_xml == True:
        add_spotbugs_plugins_to_pom_xml(plugins)
    
    
    #tree.write('pom.xml')
    tree.write(pom_xml)
    
####################################################################
# Creates one or more maven applications depending on your choice #
####################################################################
def mk_multi_mvn_apps_n_move_files_4m_multi_apps():
    
    #e.g., my-javacodeanalysis-app0
    app_name_full = '{}{}'.format(app_name_partial, array_id)
    
    #e.g. my-javacodeanalysis-app0
    app_name_full_dest_path = app_name_full
    
    #e.g., ../my_codesnippet_analysis/SpotBugs1/mvn_apps
    #or mvn_apps
    parent_dest_full_path = parent_dest_path
    
    #e.g., ../my_codesnippet_analysis/SpotBugs1/mvn_apps/checks_lib
    #or mvn_apps/checks_lib
    lib_full_path = '{}/{}'.format(parent_dest_path, lib_path)
    
    
    if use_comm_root_dir == True and use_parent_dest_path == True:
        #e.g., ../my_codesnippet_analysis/SpotBugs1
        parent_dest_full_path = '{}/{}'.format(comm_root_dir, parent_dest_path)
        #e.g., ../my_codesnippet_analysis/SpotBugs1/checks_lib
        lib_full_path = '{}/{}'.format(comm_root_dir, lib_path)
        #e.g., ../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0
        app_name_full_dest_path = '{}/{}/{}'.format(comm_root_dir, parent_dest_path, app_name_full)
        
    elif use_comm_root_dir == True:
        #e.g., ../my_codesnippet_analysis/SpotBugs1
        parent_dest_full_path = comm_root_dir
        #e.g., ../my_codesnippet_analysis/SpotBugs1/checks_lib
        lib_full_path = '{}/{}'.format(comm_root_dir, lib_path)
        #e.g., ../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0
        app_name_full_dest_path = '{}/{}'.format(comm_root_dir, app_name_full)
        
    elif use_parent_dest_path == True:
        #e.g., ../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0
        app_name_full_dest_path = '{}/{}'.format(parent_dest_path, app_name_full)
        
    #e.g., ../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0/src/main/java
    app_name_full_child_dest_path = '{}/{}'.format(app_name_full_dest_path, child_dest_path)
    #e.g., ../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis
    app_name_full_child_dest_path_pkg = '{}/{}'.format(app_name_full_child_dest_path, pkg_name)
    
    # Rename app if this is true
    if rm_auto_gen_file == True:
        # remove existing directory if they already exist
        #remove_dir_if_exist_cmd = 'cd ../my_codesnippet_analysis/SpotBugs1/mvn_apps/; rm -rf my-javacodeanalysis-app0
        remove_dir_if_exist_cmd = 'cd {}; rm -rf {}'.format(parent_dest_full_path, app_name_full)
        cmd1 = sp.run(
            remove_dir_if_exist_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )
       
    
    # create mvn app 
    #maven_app_cmd = 'cd ../my_codesnippet_analysis/SpotBugs1/mvn_apps/; mvn archetype:generate -DgroupId=myjavacodeanalysis -DartifactId=my-javacodeanalysis-app0 -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false'
    maven_app_cmd = 'cd {}; mvn archetype:generate -DgroupId={} -DartifactId={} -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false'.format(parent_dest_full_path, pkg_name_full, app_name_full)
    cmd2 = sp.run(
        maven_app_cmd, # command
        capture_output=True,
        text=True,
        shell=True
    )

    if update_pom_xml_file == True:

        # update pom.xml
        update_pom_xml(app_name_full_dest_path)

        # format the pom.xml file and put the result in pom_fmt.xml  
        #e.g., fmt_pom_xml_cmd = 'cd ../my_codesnippet_analysis/SpotBugs1/mvn_appsa/my-javacodeanalysis-app0; xmllint --format pom.xml > pom_fmt.xml'
        fmt_pom_xml_cmd = 'cd {}; xmllint --format pom.xml > pom_fmt.xml'.format(app_name_full_dest_path)
        cmd4 = sp.run(
            fmt_pom_xml_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )

        #remove the pom.xml file 
         #e.g., rv_pom_xml_cmd = 'cd ../my_codesnippet_analysis/SpotBugs1/mvn_appsa/my-javacodeanalysis-app0; rm pom.xml'
        rm_pom_xml_cmd = 'cd {}; rm pom.xml'.format(app_name_full_dest_path)
        cmd5 = sp.run(
            rm_pom_xml_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )

        #rename the pom_fmt.xml to pom.xml file
         #e.g., rm_pom_xml_cmd = 'cd ../my_codesnippet_analysis/SpotBugs1/mvn_appsa/my-javacodeanalysis-app0; mv pom_fmt.xml pom.xml'
        mv_pom_xml_cmd = 'cd {}; mv pom_fmt.xml pom.xml'.format(app_name_full_dest_path)
        cmd6 = sp.run(
            mv_pom_xml_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )
    
    
    # Copy the 'google_checks.xml' from the check_lib to the root dir of app 
    #cp_checks_xml_cmd = 'cp ../my_codesnippet_analysis/SpotBugs1/checks_lib/google_checks.xml ../my_codesnippet_analysis/SpotBugs1/mvn_appsa/my-javacodeanalysis-app0'
    cp_checks_xml_cmd = 'cp {}/{} {}'.format(lib_full_path, checkstyle_xml_checks, app_name_full_dest_path)
        
    cmd7 = sp.run(
        cp_checks_xml_cmd, # command
        capture_output=True,
        text=True,
        shell=True
    )
    
    #cp_checks_xml_cmd = 'cp ../my_codesnippet_analysis/SpotBugs1/cp checks_lib/google_checks.xml ../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0'
    cp_spot_bugs_include_xml_cmd = 'cp {}/{} {}'.format(lib_full_path, spot_bug_include_xml, app_name_full_dest_path)
        
    cmd8 = sp.run(
        cp_spot_bugs_include_xml_cmd, # command
        capture_output=True,
        text=True,
        shell=True
    )
    
    #cp_checks_xml_cmd = 'cp ../my_codesnippet_analysis/SpotBugs1/checks_lib/google_checks.xml ../my_codesnippet_analysis/SpotBugs1/mvn_appsa/my-javacodeanalysis-app0'
    cp_spot_bugs_exclude_xml_cmd = 'cp {}/{} {}'.format(lib_full_path, spot_bug_exclude_xml, app_name_full_dest_path)
        
    cmd9 = sp.run(
        cp_spot_bugs_exclude_xml_cmd, # command
        capture_output=True,
        text=True,
        shell=True
    )
    
     
    # Delete the App.java file that is created by default from src/main/java/yourpkgdir
    #e.g., rv_def_java_app_file_cmd = 'rm ../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis/App.java'
    rm_def_java_app_file_cmd = 'rm {}/{}'.format(app_name_full_child_dest_path_pkg, auto_gen_file_rm)
    cmd10 = sp.run(
        rm_def_java_app_file_cmd, # command
        capture_output=True,
        text=True,
        shell=True
    )
    
    #src_folder = src
    #../my_codesnippet_analysis/CheckStyle1/mvn_apps / my-javacodeanalysis-app 0
    src_folder = '{}/{}{}'.format(src, src_gen_app, array_id)
    #../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0 / target
    src_target_folder = '{}/{}'.format(src_folder, target_folder_path)
    #../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0 / src/test
    src_test_folder = '{}/{}'.format(src_folder, test_folder_path)
    
    if use_child_src == True:
        #../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis
        src_folder = '{}/{}{}/{}'.format(src, src_gen_app, array_id, child_src)
    
    #filenames_array_id = os.path.join('../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis', '*.java')
    file_location = os.path.join(src_folder, '{}*.{}'.format(pattern, src_type))
    
    # get all the file names and their paths
    filenames = glob.glob(file_location)
    
    # Copy or Move source code files
    #filenames_array_id = split_filenames[int(array_id)]#@@REM@@
    #source
    print('Array Id: {} Number of files: {}'.format(array_id, len(filenames)))
    #e.g dest_dir = '../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0/src/main/java/myjavacodeanalysis'
    dest_dir = '{}'.format(app_name_full_child_dest_path_pkg)
    if mv_src == True:
        #move a list of file from source to dest
        for file in filenames:
            shutil.move(file, dest_dir)
    else:
        #copy a list of file from source to dest
        for file in filenames:
            shutil.copy(file, dest_dir)
    
    # move target folder
    if copy_target_folder_path == True:
        # Delete the App.java file that is created by default from src/main/java/yourpkgdir
        #e.g., rv_def_java_app_file_cmd = 'cp -r ../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0/target ../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0'
        cd_trg_file_cmd = 'cp -r {} {}'.format(src_target_folder, app_name_full_dest_path)
        cmd11 = sp.run(
            cd_trg_file_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )
        
     #move src/test folder
    if copy_test_folder_path == True:
        # Delete the App.java file that is created by default from src/main/java/yourpkgdir
        #e.g., rv_def_java_app_file_cmd = 'cp -r ../my_codesnippet_analysis/CheckStyle1/mvn_apps/my-javacodeanalysis-app0/src/test ../my_codesnippet_analysis/SpotBugs1/mvn_apps/my-javacodeanalysis-app0'
        cd_tst_file_cmd = 'cp -r {} {}/src'.format(src_test_folder, app_name_full_dest_path)
        cmd12 = sp.run(
            cd_tst_file_cmd, # command
            capture_output=True,
            text=True,
            shell=True
        )
    


# Create maven app and move files on each process
mk_multi_mvn_apps_n_move_files_4m_multi_apps()


print('Done array {} -:)'.format(array_id))

